spring.application.name=client
server.port=9090

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/shiftsdb
spring.r2dbc.username=${DB_USER}
spring.r2dbc.password=${DB_PASSWORD}

spring.sql.init.mode=never
